(lang dune 3.23)

(name bicategorical-tt)
(version 1d48665-dirty)

(generate_opam_files true)

(source
 (github erenyenigul/bicategorical-type-theory))

(authors "Eren Yenigul <erenyenigul@gmail.com>")

(maintainers "Eren Yenigul <erenyenigul@gmail.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name bicategorical-tt)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
